### ISSUE TITLE
Document group name truncation

### ISSUE THREAD

**Issue by jrjohnson** [ilios/user-guide#18] opened 2017-04-19 15:03 UTC
As indicated in https://github.com/ilios/frontend/pull/2879#issuecomment-295283044 we will need to document that when a group with a name that approaches 60 characters is used to generate sub groups then subgroup names will be shortened automatically.

**Comment by dartajax** [comment] 2017-04-19 16:28
Closing due to this is a duplicate of #19.

**Closed by dartajax** 2017-04-19 16:28 UTC
